"""zerogen_utils — native BytePlus / Volcengine Ark Seedance 2.0 nodes.

Aggregates NODE_CLASS_MAPPINGS / NODE_DISPLAY_NAME_MAPPINGS from the native
Seedance node modules. Helper modules (nv_byteplus_asset_api, nv_byteplus_asset_cache,
api_keys, nv_seedance_upload_utils, seedance_chunked_loop_ops, seedance_types) are
NOT registered — they are imported by the node modules above.

All node ids are namespaced with a `Zerogen_` prefix to avoid collisions with
other ComfyUI node packs.
"""

from .nv_seedance_native import (
    NODE_CLASS_MAPPINGS as SEEDANCE_NATIVE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as SEEDANCE_NATIVE_DISPLAY_NAME_MAPPINGS,
)
from .nv_seedance_prep_v2 import (
    NODE_CLASS_MAPPINGS as SEEDANCE_PREP_V2_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as SEEDANCE_PREP_V2_DISPLAY_NAME_MAPPINGS,
)
from .nv_seedance_native_v2 import (
    NODE_CLASS_MAPPINGS as SEEDANCE_NATIVE_V2_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as SEEDANCE_NATIVE_V2_DISPLAY_NAME_MAPPINGS,
)
from .seedance_native_chunked_loop import (
    NODE_CLASS_MAPPINGS as SEEDANCE_NATIVE_CHUNKED_LOOP_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as SEEDANCE_NATIVE_CHUNKED_LOOP_DISPLAY_NAME_MAPPINGS,
)
from .nv_byteplus_asset_register import (
    NODE_CLASS_MAPPINGS as BYTEPLUS_ASSET_REGISTER_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as BYTEPLUS_ASSET_REGISTER_DISPLAY_NAME_MAPPINGS,
)
from .nv_byteplus_seedance_gen import (
    NODE_CLASS_MAPPINGS as BYTEPLUS_SEEDANCE_GEN_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as BYTEPLUS_SEEDANCE_GEN_DISPLAY_NAME_MAPPINGS,
)
from .nv_byteplus_seedance_multijob import (
    NODE_CLASS_MAPPINGS as BYTEPLUS_SEEDANCE_MULTIJOB_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as BYTEPLUS_SEEDANCE_MULTIJOB_DISPLAY_NAME_MAPPINGS,
)
from .nv_byteplus_seedance_submit import (
    NODE_CLASS_MAPPINGS as BYTEPLUS_SEEDANCE_SUBMIT_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as BYTEPLUS_SEEDANCE_SUBMIT_DISPLAY_NAME_MAPPINGS,
)
from .nv_seedance_fetch_task import (
    NODE_CLASS_MAPPINGS as SEEDANCE_FETCH_TASK_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as SEEDANCE_FETCH_TASK_DISPLAY_NAME_MAPPINGS,
)

NODE_CLASS_MAPPINGS = {
    **SEEDANCE_NATIVE_CLASS_MAPPINGS,
    **SEEDANCE_PREP_V2_CLASS_MAPPINGS,
    **SEEDANCE_NATIVE_V2_CLASS_MAPPINGS,
    **SEEDANCE_NATIVE_CHUNKED_LOOP_CLASS_MAPPINGS,
    **BYTEPLUS_ASSET_REGISTER_CLASS_MAPPINGS,
    **BYTEPLUS_SEEDANCE_GEN_CLASS_MAPPINGS,
    **BYTEPLUS_SEEDANCE_MULTIJOB_CLASS_MAPPINGS,
    **BYTEPLUS_SEEDANCE_SUBMIT_CLASS_MAPPINGS,
    **SEEDANCE_FETCH_TASK_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **SEEDANCE_NATIVE_DISPLAY_NAME_MAPPINGS,
    **SEEDANCE_PREP_V2_DISPLAY_NAME_MAPPINGS,
    **SEEDANCE_NATIVE_V2_DISPLAY_NAME_MAPPINGS,
    **SEEDANCE_NATIVE_CHUNKED_LOOP_DISPLAY_NAME_MAPPINGS,
    **BYTEPLUS_ASSET_REGISTER_DISPLAY_NAME_MAPPINGS,
    **BYTEPLUS_SEEDANCE_GEN_DISPLAY_NAME_MAPPINGS,
    **BYTEPLUS_SEEDANCE_MULTIJOB_DISPLAY_NAME_MAPPINGS,
    **BYTEPLUS_SEEDANCE_SUBMIT_DISPLAY_NAME_MAPPINGS,
    **SEEDANCE_FETCH_TASK_DISPLAY_NAME_MAPPINGS,
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
